---
platform: linux

image_resource:
  type: docker-image
  source: { repository: "library/golang", tag: "1.7"}

run:
  path: pipeline-repo/ci/scripts/build-service-broker.sh

inputs:
- name: pipeline-repo
- name: service-broker-repo

outputs:
- name: binary
