---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: changeit # allomov/deploy-worker
    tag: v1.0

run:
  path: pipeline-repo/ci/scripts/build.sh

inputs:
- name: pipeline-repo
- name: chaos-loris-repo
outputs:
- name: built-binary