---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: v1.3

run:
  path: pipeline-repo/ci/scripts/build-service-broker.sh

inputs:
- name: pipeline-repo
  path: go/src/github.com/Altoros/cf-chaos-loris-broker.git

outputs:
- name: binary
