---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7

run:
  path: pipeline-repo/ci/scripts/deploy-service-broker.sh

inputs:
- name: pipeline-repo
- name: service-broker-repo
