---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: v1.3

run:
  path: pipeline-repo/ci/scripts/deploy-service-broker.sh

inputs:
- name: pipeline-repo
