---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/cf-cli
    tag: v1.3

run:
  path: pipeline-repo/ci/scripts/register-service-broker.sh

inputs:
- name: pipeline-repo

outputs:
- name: binary
