---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/cf-cli
    tag: v1.0

run:
  path: pipeline-repo/ci/scripts/deploy.sh

inputs:
- name: pipeline-repo
- name: built-binary
