---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/deploy-worker
    tag: "latest"

run:
  path: pipeline-repo/ci/scripts/run-app-test.sh

inputs:
- name: pipeline-repo
