---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/test-chaos-loris
    tag: "1.1"

run:
  path: pipeline-repo/ci/scripts/run-app-test.sh

inputs:
- name: pipeline-repo
