---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/cf-cli
    tag: "1.3"

run:
  path: pipeline-repo/ci/scripts/run-app-test.sh

inputs:
- name: pipeline-repo
