resources:
- name: pipeline-repo
  type: git
  check: 1m
  source:
    uri: https://github.com/Altoros/concourse-deploy-chaos-loris.git
    branch: master
- name: chaos-loris-repo
  type: git
  source:
    uri: https://github.com/Altoros/chaos-loris.git
    branch: develop

jobs:
- name: deploy-chaos-loris
  plan:
  - aggregate:
    - get: pipeline-repo
    - get: chaos-loris-repo
  - task: build
    file: pipeline-repo/ci/tasks/build.yml
  - task: deploy
    file: pipeline-repo/ci/tasks/deploy.yml
    params: 
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

- name: deploy-service-broker
  plan:
  - aggregate:
    - get: pipeline-repo
#      passed: [deploy-chaos-loris]
  - task: build
    file: ci/tasks/build-service-broker.yml

- name: register-service-broker
  plan:
  - aggregate:
    - get: pipeline-repo
#      passed: [deploy-service-broker]
  - task: deploy
    file: ci/tasks/deploy-service-broker.yml

# - name: create-schedule
#   plan:
#     - get: pipeline-repo
#       passed: [deploy-chaos-loris]
#     - task: create-schedule
#       file: pipeline-repo/common/tasks/run-command.yml
#       params:
#         SCRIPT: ci/scripts/worker.sh
#         COMMAND: create-schedule

# - name: udpate-apps
#   plan:
#   - get: pipeline-repo
#     passed: [create-schedule]
#   - name: create-apps-in-loris
#     plan:
#     - get: pipeline-repo
#       passed: [deploy-loris]
#       serial: true
#       trigger: true
#     - task: create-apps
#       config:
#         platform: linux
#         image_resource:
#           type: docker-image
#           source:
#             repository: agf234/bosh-tools-awscli
#             tag: latest
#         run:
#           path: ./scripts/cl-create-apps.sh
#           args: []
#         params:

