resources:
- name: pipeline-repo
  type: git
  source:
    uri: https://github.com/Altoros/concourse-deploy-chaos-loris.git
    branch: master
- name: chaos-loris-repo
  type: git
  source:
    uri: https://github.com/Altoros/chaos-loris.git
    branch: master

jobs:
- name: deploy
  plan:
  - get: pipeline-repo
  - task: deploy
    file: pipeline-repo/ci/tasks/run-script.yml
    params: 
      SCRIPT: ci/scripts/cf-deploy.sh
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

- name: deploy
  plan:
  - get: pipeline-repo
  - task: deploy
    file: pipeline-repo/ci/tasks/run-script.yml

  - name: create-apps-in-loris
    plan:
      - aggregate:
        - get: pipeline-repo
          passed: [deploy-loris]
          serial: true
          trigger: true
      - task: create-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: agf234/bosh-tools-awscli
              tag: latest
          run:
            path: ./scripts/cl-create-apps.sh
            args: []
          params:

  - name: create-schedule
    plan:
      - aggregate:
        - get: pipeline-repo
          passed: [deploy-loris]
          passed: [create-apps-in-loris]
          serial: false
      - task: create-schedule
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: agf234/bosh-tools-awscli
              tag: latest
          run:
            path: ./scripts/cl-create-sched.sh
            args: []
          params:


  - name: "clean-apps"
    plan:
      - aggregate:
        - get: pipeline-repo
          passed: [deploy-loris]
          passed: [create-apps-in-loris]
          serial: true
          trigger: false
      - task: clean
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: agf234/bosh-tools-awscli
              tag: latest
          run:
            path: ./scripts/cl-cleanup.sh
            args: []
          params:


