resources:
- name: pipeline-repo
  type: git
  check: 2m
  source:
    uri: https://github.com/Altoros/concourse-deploy-chaos-loris.git
    branch: master
- name: chaos-loris-repo
  type: git
  source:
    uri: https://github.com/Altoros/chaos-loris.git
    branch: develop
- name: service-broker-repo
  type: git
  source:
    uri: https://github.com/Altoros/cf-chaos-loris-broker.git
- name: simple-victim-app
  type: git
  source:
    uri: https://github.com/allomov/super-simple-sintara-app.git

jobs:
- name: deploy-chaos-loris
  plan:
  - aggregate:
    - get: pipeline-repo
    - get: chaos-loris-repo
  - task: build
    file: pipeline-repo/ci/tasks/build.yml
  - task: deploy
    file: pipeline-repo/ci/tasks/deploy.yml
    params: 
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

- name: deploy-service-broker
  plan:
  - aggregate:
    - get: service-broker-repo 
    - get: pipeline-repo
#      passed: [deploy-chaos-loris]
  - task: build
    file: pipeline-repo/ci/tasks/build-service-broker.yml
  - task: deploy
    file: pipeline-repo/ci/tasks/deploy-service-broker.yml
    params:
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

- name: register-service-broker
  plan:
  - aggregate:
    - get: pipeline-repo
#      passed: [deploy-service-broker]
  - task: register
    file: pipeline-repo/ci/tasks/register-service-broker.yml
    params:
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}
- name: acceptance-test
  plan:
  - aggregate:
    - get: pipeline-repo
    - get: simple-victim-app
  - task: run-app-test
    file: pipeline-repo/ci/tasks/run-app-test.yml
    params:
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

#  - task: run-sched-test
#    file: pipeline-repo/common/tasks/run-acceptance-test.yml
#    params:
#      VAULT_ADDR: {{vault-address}}
#      VAULT_TOKEN: {{vault-token}}
#      FOUNDATION_NAME: {{foundation-name}}
#      PRODUCT_NAME: {{product-name}}
#  - task: run-chaos-test
#    file: pipeline-repo/common/tasks/run-acceptance-test.yml
#    params:
#      VAULT_ADDR: {{vault-address}}
#      VAULT_TOKEN: {{vault-token}}
#      FOUNDATION_NAME: {{foundation-name}}
#      PRODUCT_NAME: {{product-name}}
#
